name: My Workflow
on: push
jobs:
  job1:
    runs-on: ubuntu-latest
    steps:
      - name : Test
        run: |
          echo OPENAI_API_KEY
        env:
          OPENAI_API_KEY: ${{ secrets.OPENAI_API_KEY }}
